-- SPDX-FileCopyrightText: 2026 Mika Tammi
-- SPDX-License-Identifier: MIT OR BSD-3-Clause

{- |
Module      : Main
Description : Emit the Hello firmware as a Quartus @.mif@ file.

@
  cabal run riski5-emit-hello -- /path/to/hello.mif
  cabal run riski5-emit-hello   # writes to ./hello.mif
@

Produces a Memory Initialization File Quartus accepts for
populating on-chip BRAMs at synthesis time. The depth matches the
Top.hs imem size; any unused words are initialised with RV32I
NOPs (@0x00000013@).
-}
module Main (main) where

import Clash.Prelude qualified as CP
import Data.List (intercalate)
import Data.Word qualified as W
import Hello qualified
import System.Environment (getArgs)
import Text.Printf (printf)

{- | Number of 32-bit words the .mif describes. Must match Top.hs's
ProgSize.
-}
totalWords :: Int
totalWords = 256

main :: IO ()
main = do
  args <- getArgs
  let outPath = case args of
        (p : _) -> p
        _ -> "hello.mif"
  writeFile outPath (renderMif Hello.helloFirmwareWords)
  putStrLn ("wrote " ++ outPath ++ " (" ++ show totalWords ++ " words)")

{- | Render the program as a Quartus-compatible MIF. Pads with NOPs
up to 'totalWords'.
-}
renderMif :: [CP.BitVector 32] -> String
renderMif words_ =
  let padded = take totalWords (words_ ++ repeat nopBits)
      entries = zipWith mifEntry [0 ..] padded
   in intercalate
        "\n"
        ( [ "-- Generated by firmware/phase1/Emit.hs. Do not edit by hand."
          , "-- Regenerate with: cabal run riski5-emit-hello -- <path>"
          , ""
          , "DEPTH = " ++ show totalWords ++ ";"
          , "WIDTH = 32;"
          , "ADDRESS_RADIX = HEX;"
          , "DATA_RADIX = HEX;"
          , ""
          , "CONTENT"
          , "BEGIN"
          ]
            ++ entries
            ++ ["END;"]
        )

mifEntry :: Int -> CP.BitVector 32 -> String
mifEntry addr w = printf "    %04X : %08X;" addr (bitVectorToWord32 w)

bitVectorToWord32 :: CP.BitVector 32 -> W.Word32
bitVectorToWord32 b = fromIntegral (CP.unpack b :: CP.Unsigned 32)

-- | The canonical RV32I NOP: @ADDI x0, x0, 0@.
nopBits :: CP.BitVector 32
nopBits = 0x0000_0013
