-- SPDX-FileCopyrightText: 2026 Mika Tammi
-- SPDX-License-Identifier: MIT OR BSD-3-Clause
{-# LANGUAGE NoImplicitPrelude #-}
{-# LANGUAGE RebindableSyntax #-}

{- |
Module      : Main
Description : Boot-ROM generator (B-2..B-5).

Emits both:

  * @boot_rom_step.{c,h,_types.h}@ — the SDRAM-loader state
    machine, generated by Copilot from a pure Haskell stream
    spec.
  * @start.c@ — the bare-metal wrapper. Sets the stack pointer,
    polls JTAG-UART each tick, drives @step()@ until
    @boot_done@ goes True, then issues the RISC-V Linux nommu
    boot ABI handoff (@a0=0@, @a1=&dtb@, @jr 0x8000_0000@).

Both files come from this Haskell program — no hand-written C
sits in the repo. The wrapper is a string template stored
in 'startC'.

== Wire-protocol (B-2)

Matches @firmware/phase1/LinuxBoot.hs@ exactly so the host-side
@scripts/load-linux.sh@ / @riski5-load-stream@ keep working
unchanged:

@
  bytes 0..3   : little-endian kernel word count K
  bytes 4..7   : little-endian DTB    word count D
  bytes 8..    : K × 32-bit LE kernel words
  bytes (8+4K) : D × 32-bit LE DTB    words
@

== State machine

@phase@ encodes which byte of which header / payload word is
expected next:

@
  0..3 : reading byte i of kernel word count
  4..7 : reading byte (i-4) of DTB word count
  8    : streaming payload words to SDRAM (sub-state via 'shift')
  9    : done
@

Each tick:

  - The wrapper updates the @uart_data@ extern from
    @*(volatile uint32_t*)0x1000_0000@.
  - 'step()' reads it, checks bit 15 (RVALID).
  - If RVALID, the state machine consumes one byte and advances.
  - If we just completed a 4-byte word in phase 8, fire the
    @sdram_write@ trigger.
  - If that was the last word, fire @boot_finish@ with the
    kernel byte count and set @boot_done = true@; the wrapper
    exits the loop and does the boot-ABI handoff.

Usage:

> riski5-boot-rom-gen <output-dir>

Emits the four files above.
-}
module Main (main) where

import Copilot.Compile.C99 (compile)
import GHC.IO.Encoding (setLocaleEncoding, utf8)
import Language.Copilot
import qualified Prelude as P
import Prelude (FilePath, IO, String, ($))
import qualified System.Directory as Dir
import System.Environment (getArgs)
import System.Exit (die)
import System.FilePath ((</>))

main :: IO ()
main = do
  -- Force UTF-8 stdio + writeFile encoding. Nix's build sandbox
  -- runs under LC_ALL=C, which would otherwise reject the
  -- non-ASCII bytes in our string-literal C-comment templates.
  setLocaleEncoding utf8
  args <- getArgs
  outDir <- case args of
    [d] -> P.pure d
    _ -> die "usage: riski5-boot-rom-gen <output-dir>"

  Dir.createDirectoryIfMissing P.True outDir

  -- Copilot writes to the *current* working directory; cd in.
  oldCwd <- Dir.getCurrentDirectory
  Dir.setCurrentDirectory outDir
  reified <- reify bootRomSpec
  compile "boot_rom_step" reified
  Dir.setCurrentDirectory oldCwd

  -- Wrapper. Hand-written-as-a-Haskell-string so the build-time
  -- artifact is the only C surface; no .c file ever sits in the
  -- repo.
  P.writeFile (outDir </> "start.c") startC

  P.putStrLn $ "Wrote: " P.++ (outDir </> "boot_rom_step.c")
  P.putStrLn $ "Wrote: " P.++ (outDir </> "boot_rom_step.h")
  P.putStrLn $ "Wrote: " P.++ (outDir </> "boot_rom_step_types.h")
  P.putStrLn $ "Wrote: " P.++ (outDir </> "start.c")

-- ------------------------------------------------------------------
-- Copilot spec — SDRAM-loader state machine
-- ------------------------------------------------------------------

bootRomSpec :: Spec
bootRomSpec = do
  -- ----- Inputs ------------------------------------------------
  -- Each tick the wrapper updates @uart_data@ from the JTAG-UART
  -- DATA register. Bit 15 = RVALID, bits 7:0 = byte data.
  let uartData :: Stream Word32
      uartData = extern "uart_data" P.Nothing

      isRValid :: Stream Bool
      isRValid = (uartData .&. constW32 0x8000) /= constW32 0

      uByte :: Stream Word32
      uByte = uartData .&. constW32 0xFF

      -- ----- State streams (initial value, then recursive update)
      phase :: Stream Word8
      phase = [0] ++ phaseNext

      shift :: Stream Word32 -- 0, 8, 16, 24 (only meaningful in phase 8)
      shift = [0] ++ shiftNext

      kAcc :: Stream Word32 -- accumulating kernel word count
      kAcc = [0] ++ kAccNext

      dAcc :: Stream Word32 -- accumulating DTB word count
      dAcc = [0] ++ dAccNext

      wordAcc :: Stream Word32 -- assembling current SDRAM word (phase 8)
      wordAcc = [0] ++ wordAccNext

      written :: Stream Word32 -- words written to SDRAM so far
      written = [0] ++ writtenNext

      -- ----- Predicates --------------------------------------
      readingK = phase < 4
      readingD = (phase >= 4) && (phase < 8)
      streaming = phase == 8
      doneP = phase == 9
      consume = isRValid && not doneP

      atWordEnd :: Stream Bool
      atWordEnd = streaming && (shift == constW32 24)

      finishesNow :: Stream Bool
      finishesNow =
        consume
          && atWordEnd
          && ((written + constW32 1) >= (kAcc + dAcc))

      -- ----- Updates -----------------------------------------
      kAccNext :: Stream Word32
      kAccNext =
        mux (consume && readingK) (kAcc .|. (uByte .<<. kdShift)) kAcc

      dAccNext :: Stream Word32
      dAccNext =
        mux (consume && readingD) (dAcc .|. (uByte .<<. kdShift)) dAcc

      -- Byte-shift for kAcc / dAcc reads. phase mod 4 maps to 0/1/2/3
      -- (LE byte index); multiplied by 8 gives the bit shift.
      kdShift :: Stream Word32
      kdShift =
        mux (phase == 0 || phase == 4) (constW32 0) $
          mux (phase == 1 || phase == 5) (constW32 8) $
            mux (phase == 2 || phase == 6) (constW32 16) (constW32 24)

      wordAccNext :: Stream Word32
      wordAccNext =
        mux
          (consume && streaming)
          ( mux
              atWordEnd
              (constW32 0) -- reset after writing
              (wordAcc .|. (uByte .<<. shift))
          )
          ( mux
              ((phase == 7) && consume) -- entering phase 8 next tick
              (constW32 0)
              wordAcc
          )

      shiftNext :: Stream Word32
      shiftNext =
        mux
          (consume && streaming)
          (mux atWordEnd (constW32 0) (shift + constW32 8))
          (constW32 0)

      writtenNext :: Stream Word32
      writtenNext =
        mux (consume && atWordEnd) (written + constW32 1) written

      phaseNext :: Stream Word8
      phaseNext =
        mux (not consume) phase $
          mux finishesNow (constW8 9) $
            mux streaming (constW8 8) $
              phase + constW8 1

      -- ----- Trigger arguments -------------------------------
      sdramAddr :: Stream Word32
      sdramAddr = constW32 0x80000000 + (written * constW32 4)

      -- The 32-bit word about to land in SDRAM. wordAcc holds the
      -- low 24 bits; the just-consumed byte lands in bits [31:24].
      fullWord :: Stream Word32
      fullWord = wordAcc .|. (uByte .<<. constW32 24)

      kernelBytes :: Stream Word32
      kernelBytes = kAcc * constW32 4

  -- ----- Triggers ----------------------------------------------
  -- Fires once per assembled word: write to SDRAM at the running
  -- pointer.
  trigger "sdram_write" (consume && atWordEnd) [arg sdramAddr, arg fullWord]

  -- Fires exactly once when the state machine transitions to
  -- phase 9. Wrapper captures kernel-byte-count for the
  -- a1 = 0x80000000 + kbytes handoff and flips boot_done.
  trigger "boot_finish" finishesNow [arg kernelBytes]

-- (Copilot already exports 'constW8' / 'constW32' /
-- 'constant' wrappers that turn Haskell-side numeric values into
-- typed 'Stream' constants. We use those directly.)

-- ------------------------------------------------------------------
-- Wrapper start.c — generated, never hand-edited
-- ------------------------------------------------------------------

{- |
The bare-metal wrapper. Imported as a string and written verbatim
to @<outDir>/start.c@ at codegen time. Stays in Haskell (rather
than as a checked-in .c file) so the build's only C surface is
machine-generated, satisfying the "no hand-written C" rule.

== What it owns

  * @_start@ — the linker entry. Sets @sp@, calls @c_main@.
  * @c_main@ — runs the load loop:
      - Emit 'L' to UART.
      - Update @uart_data@ extern, call @step()@, repeat until
        @boot_done@.
      - Emit 'D' to UART.
      - Linux nommu boot-ABI handoff: @a0=0@, @a1=&dtb@,
        @jr 0x8000_0000@.
  * The @sdram_write@, @boot_finish@ trigger function bodies.
    Copilot declares them extern; the wrapper provides the
    implementations as direct MMIO stores.
  * The @uart_data@ stream-extern variable. Copilot declares it
    extern; the wrapper allocates it.

== MMIO addresses

Sourced from @src/Riski5/MemMap.hs@: UART_DATA = 0x10000000,
SDRAM base = 0x80000000, SRAM top = 0x20080000. These string
literals are the only place the addresses get baked into the
generated boot ROM; if they change we update them here.
-}
startC :: String
startC =
  P.unlines
    [ "/* AUTO-GENERATED by tools/boot-rom/Main.hs — DO NOT EDIT */"
    , "/* Wrapper around the Copilot-generated step(); owns the"
    , "   stack pointer setup, the load loop, the MMIO trigger"
    , "   bodies, and the RISC-V Linux nommu boot-ABI handoff. */"
    , ""
    , "#include <stdint.h>"
    , "#include <stdbool.h>"
    , "#include \"boot_rom_step.h\""
    , ""
    , "/* MMIO addresses — match src/Riski5/MemMap.hs. */"
    , "#define UART_DATA_ADDR 0x10000000U"
    , "#define KERNEL_BASE    0x80000000U"
    , "#define SRAM_TOP       0x20080000U"
    , ""
    , "/* Copilot-extern: the wrapper updates this each tick. */"
    , "uint32_t uart_data = 0;"
    , ""
    , "/* Set by boot_finish; signals the load loop to exit. */"
    , "static volatile bool     boot_done         = false;"
    , "static volatile uint32_t boot_kernel_bytes = 0;"
    , ""
    , "/* Trigger bodies — Copilot's step() calls these by name"
    , "   when their corresponding stream-guard fires. */"
    , ""
    , "void sdram_write(uint32_t addr, uint32_t word)"
    , "{"
    , "    *(volatile uint32_t *)addr = word;"
    , "}"
    , ""
    , "void boot_finish(uint32_t kbytes)"
    , "{"
    , "    boot_kernel_bytes = kbytes;"
    , "    boot_done         = true;"
    , "}"
    , ""
    , "/* Status-byte helper — direct MMIO write to the JTAG-UART"
    , "   DATA register. Used for the 'L' / 'D' markers around"
    , "   the load. */"
    , "static inline void uart_putc(char c)"
    , "{"
    , "    *(volatile uint32_t *)UART_DATA_ADDR = (uint32_t)c;"
    , "}"
    , ""
    , "/* ----- Entry: linker drops _start at PC 0 ------------- */"
    , ""
    , "/* C wrapper of the load loop + boot-ABI handoff. */"
    , "__attribute__((noreturn, used))"
    , "void c_main(void)"
    , "{"
    , "    uart_putc('L');"
    , ""
    , "    /* RVALID-gated polling loop. The Copilot stream guards"
    , "       all start with `(uart_data_cpy & 0x8000) != 0`, so when"
    , "       RVALID=0 every guard is False and step() leaves all"
    , "       state arrays unchanged — semantically a no-op. Skipping"
    , "       step() in that case turns the inner spin into a 3-instr"
    , "       loop (lw / and / beqz) instead of ~150 instr per poll,"
    , "       lifting silicon throughput from ~2 KB/s to JTAG-UART-"
    , "       limited (~100 KB/s). The masked load also doubles as"
    , "       the read of `uart_data` into the Copilot extern, which"
    , "       step() picks up via `uart_data_cpy = uart_data`. */"
    , "    while (!boot_done) {"
    , "        uint32_t w = *(volatile uint32_t *)UART_DATA_ADDR;"
    , "        if (w & 0x8000U) {"
    , "            uart_data = w;"
    , "            step();"
    , "        }"
    , "    }"
    , ""
    , "    uart_putc('D');"
    , ""
    , "    /* RISC-V Linux nommu boot ABI:"
    , "       a0 = hartid (0), a1 = &dtb (KERNEL_BASE + kbytes),"
    , "       sp = SRAM_TOP, pc = KERNEL_BASE. */"
    , "    register uint32_t a0 __asm__(\"a0\") = 0;"
    , "    register uint32_t a1 __asm__(\"a1\") ="
    , "        KERNEL_BASE + boot_kernel_bytes;"
    , "    __asm__ volatile ("
    , "        \"li t0, %2\\n\\t\""
    , "        \"jr t0\\n\\t\""
    , "        : : \"r\"(a0), \"r\"(a1), \"i\"(KERNEL_BASE)"
    , "        : \"t0\""
    , "    );"
    , "    __builtin_unreachable();"
    , "}"
    , ""
    , "/* Linker-supplied .bss bounds. _start zeros this range"
    , "   before any C runs — required because the bitstream pads"
    , "   BRAM with 0x00000013 (NOP) past .text + .data, so any"
    , "   static var without an explicit initialiser starts at"
    , "   0x13 (truthy for bool!) instead of 0 if we don't"
    , "   actively zero the region. */"
    , "extern char __bss_start[];"
    , "extern char __bss_end[];"
    , ""
    , "/* The very first instruction the core executes after reset."
    , "   Owns: sp setup, .bss zero-fill, jump to c_main."
    , "   `section(\".text.entry\")` puts this in its own input"
    , "   section so the linker script can place it at offset 0 of"
    , "   .text — i.e. at the riski5 reset PC. Without this GCC"
    , "   may reorder functions within start.o (especially with"
    , "   -Os + naked) and the reset PC ends up inside an"
    , "   arbitrary helper, crashing on cycle 0."
    , ""
    , "   The .bss zero-fill is a tight RV32I word-store loop in"
    , "   inline asm; we can't call out to memset (no libc) and"
    , "   we can't write the loop in C either because sp is not"
    , "   yet initialised — naked + asm is the only option. */"
    , "__attribute__((noreturn, naked, section(\".text.entry\")))"
    , "void _start(void)"
    , "{"
    , "    __asm__ volatile ("
    , "        \"li   sp, %0\\n\\t\""
    , "        \"la   t0, __bss_start\\n\\t\""
    , "        \"la   t1, __bss_end\\n\\t\""
    , "    \"1:  bge  t0, t1, 2f\\n\\t\""
    , "        \"sw   zero, 0(t0)\\n\\t\""
    , "        \"addi t0, t0, 4\\n\\t\""
    , "        \"j    1b\\n\\t\""
    , "    \"2:  j    c_main\\n\\t\""
    , "        : : \"i\"(SRAM_TOP)"
    , "    );"
    , "    __builtin_unreachable();"
    , "}"
    ]
