-- SPDX-FileCopyrightText: 2026 Mika Tammi
-- SPDX-License-Identifier: MIT OR BSD-3-Clause
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoStarIsType #-}

{- |
Module      : Top
Description : DE2 top entity — Clash → Verilog → Quartus → .sof.

Synthesises into a Verilog module named @riski5@ that matches the
port names in @pkgs/riski5-core/Riski5.qsf@. The UART slave bus is
exposed as five top-level output ports plus one input port
(@UART_RDATA@) so that the outer @riski5_top.v@ wrapper (generated
in @pkgs/riski5-core/package.nix@) can instantiate the Altera
@altera_avalon_jtag_uart@ IP at that boundary — sim still sees
'jtagUartSim' via 'Riski5.Soc.socSim', hardware sees the real IP,
and the core does not need to know which.

Baked-in firmware: the @Hello@ image from @firmware/phase1/Hello.hs@
— boots, UART-banners @hello, world\\n@, runs a SRAM self-test, and
displays the result on the LCD. At first hardware run this is the
canonical end-to-end smoke test for the core, bus, SRAM, LCD and
UART path combined.
-}
module Top (
  topEntity,
) where

import Clash.Annotations.TH (makeTopEntityWithName)
import Clash.Prelude
import Hello (helloFirmwareWords)
import Riski5.AvalonMm (AvalonMmBus (..))
import Riski5.Lcd (LcdPins (..))
import Riski5.Sdram (SdramIpBus (..), SdramIpReply (..))
import Riski5.Soc (SocIn (..), SocOut (..), soc)
import Riski5.Sram (SramPins (..))
import Prelude qualified as P

-- * Clock domain --------------------------------------------------

{- | 30 MHz core domain. On the DE2 the 30 MHz clock is produced by
an Altera ALTPLL instantiated in @riski5_top.v@ (generated by
@pkgs/riski5-core/package.nix@) from the on-board 50 MHz oscillator:
@50 × 3 / 5 = 30 MHz@. 30 MHz sits 4 MHz below the fit-report Fmax
of the pipelined core + Altera JTAG UART IP combination (34.05 MHz
measured April 2026), so the design closes timing with real margin
instead of grazing Fmax. Phase 1E will hunt the critical path and
retarget upwards — likely back to 40 MHz or beyond.

The Clash top takes that PLL output as its input clock rather than
owning the PLL itself — both the riski5 SoC and the Altera JTAG UART
IP need to be clocked on the same edge, and the easiest way to
guarantee that is to share one source of truth for @clk30@ at the
Verilog-wrapper level. Reset is held asserted until the PLL locks
and KEY0 is released.
-}
createDomain
  vSystem
    { vName = "Dom30"
    , vPeriod = 25000
    , vResetKind = Asynchronous
    , vResetPolarity = ActiveLow
    }

-- * Firmware --------------------------------------------------------

{- | 1024-word (4 KB) instruction memory — sized for the Phase 2B+
Hello firmware (~580 words after the SRAM-diagnostics UART hex
path landed). Unused tail words are NOPs so pc-overflow wraps to
NOP rather than producing undefined behaviour. M4K cost is 8
blocks (4608 bits each at 128×36); still a small slice of the
Cyclone II EP2C35's ~105-block pool.
-}
type ProgSize = 1024

-- | 64-word data memory. Phase-1B Hello firmware doesn't touch it.
type DataSize = 64

firmwareImage :: Vec ProgSize (BitVector 32)
firmwareImage =
  $(listToVecTH (P.take 1024 (helloFirmwareWords P.++ P.repeat (0x0000_0013 :: BitVector 32))))

dataImage :: Vec DataSize (BitVector 32)
dataImage = repeat 0

-- * Top entity -----------------------------------------------------

{- |
DE2 top-level entity.
-}
topEntity ::
  {- | 40 MHz clock generated by an Altera ALTPLL sitting in the
  @riski5_top.v@ wrapper outside the Clash module.
  -}
  "CLOCK_30" ::: Clock Dom30 ->
  {- | Active-low reset, held asserted until the PLL locks and
  @KEY0@ is released.
  -}
  "RESET_30_N" ::: Reset Dom30 ->
  "KEY" ::: Signal Dom30 (BitVector 4) ->
  "SW" ::: Signal Dom30 (BitVector 18) ->
  {- | What the SRAM is currently driving on its DQ bus, sampled
  combinationally. The pin-multiplex wrapper produced by the
  Nix build resolves this against 'SRAM_DQ_O' / 'SRAM_DQ_OE'
  on the actual bidirectional SRAM_DQ[15:0] FPGA pads.
  -}
  "SRAM_DQ_I" ::: Signal Dom30 (BitVector 16) ->
  {- | Read data returned by the Altera JTAG UART IP for the last
  bus transaction. Driven by @altera_avalon_jtag_uart@'s
  @av_readdata@ output in the @riski5_top.v@ wrapper generated
  by @pkgs/riski5-core/package.nix@.
  -}
  "UART_RDATA" ::: Signal Dom30 (BitVector 32) ->
  {- | Complement of the IP's @av_waitrequest@. Low for the first
  cycle of every UART transaction (when the IP latches write-data
  registered); the SoC's stall logic freezes the core until this
  goes high, so @av_writedata@ is still stable at the edge the
  IP's FIFO captures it.
  -}
  "UART_READY" ::: Signal Dom30 Bool ->
  {- | 16-bit read-data returned by the Altera SDRAM Controller IP
  on @za_data@. Valid on the cycle @SDRAM_VALID@ is asserted.
  -}
  "SDRAM_RDATA" ::: Signal Dom30 (BitVector 16) ->
  {- | SDRAM read-data-valid strobe (@za_valid@) — rises on the
  cycle the IP has the read-data ready on @SDRAM_RDATA@.
  -}
  "SDRAM_VALID" ::: Signal Dom30 Bool ->
  {- | Complement of the SDRAM IP's @za_waitrequest@ — the core
  stalls while this is low, same stall mechanism as the JTAG UART.
  -}
  "SDRAM_READY" ::: Signal Dom30 Bool ->
  ""
    ::: ( "LEDR" ::: Signal Dom30 (BitVector 18)
        , "LEDG" ::: Signal Dom30 (BitVector 9)
        , "LCD_DATA" ::: Signal Dom30 (BitVector 8)
        , "LCD_RS" ::: Signal Dom30 Bit
        , "LCD_RW" ::: Signal Dom30 Bit
        , "LCD_EN" ::: Signal Dom30 Bit
        , "LCD_ON" ::: Signal Dom30 Bit
        , "LCD_BLON" ::: Signal Dom30 Bit
        , "SRAM_ADDR" ::: Signal Dom30 (BitVector 18)
        , "SRAM_DQ_O" ::: Signal Dom30 (BitVector 16)
        , "SRAM_DQ_OE" ::: Signal Dom30 Bool
        , "SRAM_CE_N" ::: Signal Dom30 Bit
        , "SRAM_OE_N" ::: Signal Dom30 Bit
        , "SRAM_WE_N" ::: Signal Dom30 Bit
        , "SRAM_UB_N" ::: Signal Dom30 Bit
        , "SRAM_LB_N" ::: Signal Dom30 Bit
        , -- UART bus tap — routed in @riski5_top.v@ to the Altera
          -- @altera_avalon_jtag_uart@ IP's Avalon-MM slave. The IP
          -- consumes these signals and drives @UART_RDATA@ back in
          -- on the same (Dom30) cycle.
          "UART_SEL" ::: Signal Dom30 Bool
        , "UART_ADDR" ::: Signal Dom30 (BitVector 32)
        , "UART_WDATA" ::: Signal Dom30 (BitVector 32)
        , "UART_BE" ::: Signal Dom30 (BitVector 4)
        , "UART_RE" ::: Signal Dom30 Bool
        , -- SDRAM bus tap — 16-bit Avalon-MM master signals produced
          -- by the 32 ↔ 16 adapter 'Riski5.Sdram.sdram'. Routed by
          -- @riski5_top.v@ to the Altera SDRAM Controller IP.
          "SDRAM_CS" ::: Signal Dom30 Bool
        , "SDRAM_ADDR" ::: Signal Dom30 (BitVector 22)
        , "SDRAM_WDATA" ::: Signal Dom30 (BitVector 16)
        , "SDRAM_BE" ::: Signal Dom30 (BitVector 2)
        , "SDRAM_RD" ::: Signal Dom30 Bool
        , "SDRAM_WR" ::: Signal Dom30 Bool
        )
topEntity
  clk30
  rst30
  keyS
  swS
  sramDqInS
  uartRdataS
  uartReadyS
  sdramRdataS
  sdramValidS
  sdramReadyS =
  withClockResetEnable clk30 rst30 enableGen
    $ let sdramReplyS =
            (\d v r -> SdramIpReply {sirRdata = d, sirValid = v, sirWaitrequest = P.not r})
              <$> sdramRdataS
              <*> sdramValidS
              <*> sdramReadyS
          inS =
            SocIn
              <$> swS
              <*> keyS
              <*> sramDqInS
              <*> uartRdataS
              <*> uartReadyS
              <*> sdramReplyS
          outS = soc firmwareImage dataImage inS
          ledrS = soLedR <$> outS
          ledgS = soLedG <$> outS
          lcdDataS = lcdData . soLcdPins <$> outS
          lcdRsS = lcdRs . soLcdPins <$> outS
          lcdRwS = lcdRw . soLcdPins <$> outS
          lcdEnS = lcdE . soLcdPins <$> outS
          lcdOnS = pure high
          -- LCD_BLON is active-HIGH per the DE2 schematic
          -- (pin K2 → R14/680Ω → base of Q5 8050 NPN → BL pin of
          -- the LCD module). Hardware on this brand-new board
          -- has no backlight LED installed (T19a). Drive HIGH
          -- to match schematic intent.
          lcdBlonS = pure high
          sramAddrS = sramAddr . soSramPins <$> outS
          sramDqOutS = sramDqOut . soSramPins <$> outS
          sramDqOeS = sramDqOe . soSramPins <$> outS
          sramCeNS = sramCeN . soSramPins <$> outS
          sramOeNS = sramOeN . soSramPins <$> outS
          sramWeNS = sramWeN . soSramPins <$> outS
          sramUbNS = sramUbN . soSramPins <$> outS
          sramLbNS = sramLbN . soSramPins <$> outS
          uartBusS = soUartBus <$> outS
          uartSelS = ambSel <$> uartBusS
          uartAddrS = ambAddr <$> uartBusS
          uartWdataS = ambWdata <$> uartBusS
          uartBeS = ambBe <$> uartBusS
          uartReS = ambRe <$> uartBusS
          sdramBusS = soSdramBus <$> outS
          sdramCsS = sibCs <$> sdramBusS
          sdramAddrOutS = sibAddr <$> sdramBusS
          sdramWdataOutS = sibWdata <$> sdramBusS
          sdramBeS = sibBe <$> sdramBusS
          sdramRdS = sibRd <$> sdramBusS
          sdramWrS = sibWr <$> sdramBusS
       in ( ledrS
          , ledgS
          , lcdDataS
          , lcdRsS
          , lcdRwS
          , lcdEnS
          , lcdOnS
          , lcdBlonS
          , sramAddrS
          , sramDqOutS
          , sramDqOeS
          , sramCeNS
          , sramOeNS
          , sramWeNS
          , sramUbNS
          , sramLbNS
          , uartSelS
          , uartAddrS
          , uartWdataS
          , uartBeS
          , uartReS
          , sdramCsS
          , sdramAddrOutS
          , sdramWdataOutS
          , sdramBeS
          , sdramRdS
          , sdramWrS
          )

{- | Exported Clash-usable top-entity annotation so
@clash --verilog Top.hs@ emits a module named @riski5@ with the
port names declared above.
-}
makeTopEntityWithName 'topEntity "riski5"
