-- SPDX-FileCopyrightText: 2026 Mika Tammi
-- SPDX-License-Identifier: MIT OR BSD-3-Clause
{-# LANGUAGE OverloadedStrings #-}

{- |
Module      : Riski5.Elf
Description : Firmware → raw bytes + assembly + ELF via binutils.

Turns a @[Word32]@ instruction stream (the output of
@Riski5.Asm.assemble@) into three on-disk forms:

  * A flat @.bin@ of the code bytes, little-endian. The
    simulation path ('Riski5.Sram.sramSim', the verilambda
    hwsim test, custom tools) consumes this directly.
  * An assembly stub @.s@ — one @.word 0x…@ per retired
    instruction, grouped under a single @.text.firmware@
    section. Pure @.word@ emission keeps the assembler
    honest: no mnemonic lookup, no implicit relaxations;
    the bytes hit the ELF exactly as we planned.
  * A linker script @.ld@ placing @.text.firmware@ at
    @0x8000_0000@ (Spike's default RAM base — the RV
    convention that OpenSBI, Linux, and every Spike
    example use).

The three are then glued by @riscv32-none-elf-as@ +
@riscv32-none-elf-ld@ into a proper ELF, available on
@$PATH@ via the devshell's @pkgsCross.riscv32-embedded@
binutils.

=== Why this approach

The initial draft of this module hand-rolled a 92-byte
ELF32 header. Spike refused to load it ("Memory address
0x0 is invalid", then a @e_shstrndx < e_shnum@ assertion).
Rather than chase ELF-spec corners, we lean on real binutils:

  * @as@ owns the assembly-to-object translation — if a
    new instruction family needs a custom section flag,
    we just emit the right directive instead of re-learning
    the object-file format.
  * @ld@ owns the address-placement + entry-point machinery.
    Moving the base address is a one-line edit to 'linkerScript'
    rather than a cascade of header fixups.
  * We keep @.bin@ emission for everything that doesn't need
    an ELF (MIF generation, verilambda harness data, tests
    that just want the bytes).
-}
module Riski5.Elf (
  -- * The one-call entry point
  buildElf,

  -- * Lower-level pieces (for tooling that wants them without the

  -- full @as@+@ld@ round-trip)
  renderAsm,
  renderLinkerScript,
  rawBinary,

  -- * Conventions
  spikeElfBaseAddr,
  defaultAssembler,
  defaultLinker,
) where

import Data.Binary.Put (putWord32le, runPut)
import Data.ByteString.Lazy (ByteString)
import Data.ByteString.Lazy qualified as BL
import Data.Word (Word32)
import System.FilePath ((</>))
import System.IO.Temp (withSystemTempDirectory)
import System.Process (callProcess)
import Text.Printf (printf)

-- * Conventions

{- | RISC-V convention for RAM base. Spike defaults its primary
memory region to @[0x8000_0000, 0x8000_0000 + 2 GiB)@ — placing
firmware here avoids any @-m@ massaging and matches every Spike
example in upstream. Our Clash core's firmware still lives at
@0x0@ in the DE2 memory map; the Layer-1.5 Spike-vs-Core diff
compares /architectural/ state (GPRs, CSRs, post-state), which
is absolute-PC-independent as long as both sides retire the same
instruction bits on equivalent operands.
-}
spikeElfBaseAddr :: Word32
spikeElfBaseAddr = 0x8000_0000

-- | Default assembler executable. Resolved from the devshell PATH.
defaultAssembler :: FilePath
defaultAssembler = "riscv32-none-elf-as"

-- | Default linker executable. Resolved from the devshell PATH.
defaultLinker :: FilePath
defaultLinker = "riscv32-none-elf-ld"

-- * Pure emitters

{- | Render the instruction stream as a flat little-endian byte
string — exactly the @[Word32]@ interpreted as LE. This is the
@.bin@ the verilambda simulation harness, the MIF generator,
and one-off tests all consume.
-}
rawBinary :: [Word32] -> ByteString
rawBinary = runPut . mapM_ putWord32le

{- | Render an assembly file one @.word@ directive per instruction.

Opens a single @.text.firmware@ section with @ax@ (alloc + exec)
flags and the @progbits@ type, declares @_start@ as the entry
label, then emits each word as @  .word 0xXXXXXXXX@. No mnemonic
translation, no pseudo-ops — the assembler is doing byte emission
only.
-}
renderAsm :: [Word32] -> String
renderAsm instrWords =
  unlines $
    [ "# Auto-generated by Riski5.Elf.renderAsm — do not edit by hand."
    , "# Regenerate by re-running the tool that produced it"
    , "# (firmware/phase1/Emit.hs for Hello, or the test harness"
    , "# for catalog programs)."
    , ""
    , ".section .text.firmware, \"ax\", @progbits"
    , ".global _start"
    , "_start:"
    ]
      <> fmap wordLine (zip [0 ..] instrWords)
 where
  wordLine :: (Int, Word32) -> String
  wordLine (idx, w) =
    printf "  .word 0x%08x  # 0x%04x" w (idx * 4 :: Int)

{- | Render a linker script placing @.text.firmware@ at @baseAddr@
and marking @_start@ as the entry symbol. One section, one region —
phase-1 firmware has no @.data@ or @.bss@ by design (the Asm eDSL
emits code only).
-}
renderLinkerScript :: Word32 -> String
renderLinkerScript baseAddr =
  unlines
    [ "/* Auto-generated by Riski5.Elf.renderLinkerScript. Do not edit. */"
    , "OUTPUT_ARCH(riscv)"
    , "OUTPUT_FORMAT(\"elf32-littleriscv\")"
    , "ENTRY(_start)"
    , ""
    , "SECTIONS {"
    , "  . = " <> printf "0x%08x" baseAddr <> ";"
    , "  .text.firmware : {"
    , "    KEEP(*(.text.firmware))"
    , "    *(.text)"
    , "    *(.text.*)"
    , "  }"
    , ""
    , "  /DISCARD/ : {"
    , "    *(.comment)"
    , "    *(.note*)"
    , "    *(.riscv.attributes)"
    , "  }"
    , "}"
    ]

-- * The glue: as + ld

{- | Assemble and link a @[Word32]@ instruction stream into an
ELF32 little-endian RISC-V executable loaded at @baseAddr@.

Uses a fresh temporary directory for the intermediate @.s@ / @.o@
/ @.ld@ files, which is cleaned up after 'BL.readFile' returns
the final ELF bytes. The devshell's @pkgsCross.riscv32-embedded@
binutils is on PATH; override 'defaultAssembler' / 'defaultLinker'
if you need a different toolchain pin.
-}
buildElf :: Word32 -> [Word32] -> IO ByteString
buildElf baseAddr instrWords =
  withSystemTempDirectory "riski5-elf" $ \dir -> do
    let asmPath = dir </> "firmware.s"
        objPath = dir </> "firmware.o"
        ldsPath = dir </> "firmware.ld"
        elfPath = dir </> "firmware.elf"
    writeFile asmPath (renderAsm instrWords)
    writeFile ldsPath (renderLinkerScript baseAddr)
    callProcess
      defaultAssembler
      [ "-march=rv32i"
      , "-mabi=ilp32"
      , "-o"
      , objPath
      , asmPath
      ]
    callProcess
      defaultLinker
      [ "-T"
      , ldsPath
      , "-o"
      , elfPath
      , objPath
      ]
    BL.readFile elfPath
