# SPDX-FileCopyrightText: 2026 Mika Tammi
# SPDX-License-Identifier: MIT OR BSD-3-Clause
#
# Generic version of pkgs/coremark/gen-coremark-hs.py: convert a
# raw .bin (the output of `riscv64-unknown-linux-gnu-objcopy -O
# binary`) into a Haskell module that exports the bytes as a
# `[BitVector 32]` literal. Used by the riski5-core-* Nix variants
# to overlay machine-generated firmware into the imem.
#
# Usage:
#   python3 gen-bin-hs.py <bin-path> <out.hs> <module-name> <symbol-name>
#
# Example (B-* boot ROM):
#   python3 gen-bin-hs.py boot_rom.bin LinuxBoot.hs \
#       LinuxBoot linuxBootFirmwareWords
#
# Result is a complete .hs file:
#
#     module <module-name> ( <symbol-name> ) where
#     import Clash.Prelude (BitVector)
#     <symbol-name> :: [BitVector 32]
#     <symbol-name> =
#       [ 0x........
#       , ...
#       ]
#
# The bin is interpreted as a stream of little-endian 32-bit
# words (GCC's RV32 ILP32 default). Trailing bytes that don't
# round to a 4-byte boundary are zero-padded.
import struct
import sys


def main() -> int:
    if len(sys.argv) != 5:
        sys.stderr.write(
            "usage: gen-bin-hs.py <bin> <out.hs> <module> <symbol>\n"
        )
        return 2

    bin_path, out_path, mod_name, sym_name = sys.argv[1:5]

    with open(bin_path, "rb") as f:
        data = f.read()

    pad = (-len(data)) % 4
    data += b"\x00" * pad

    word_count = len(data) // 4
    words = list(struct.unpack(f"<{word_count}I", data))

    with open(out_path, "w") as f:
        f.write(
            "-- SPDX-FileCopyrightText: 2026 Mika Tammi\n"
            "-- SPDX-License-Identifier: MIT OR BSD-3-Clause\n"
            "--\n"
            f"-- Auto-generated by pkgs/lib/gen-bin-hs.py from {bin_path}.\n"
            "-- DO NOT EDIT.\n"
            "{-# LANGUAGE DataKinds #-}\n"
            "{-# LANGUAGE NoStarIsType #-}\n"
            "\n"
            f"module {mod_name} (\n"
            f"  {sym_name},\n"
            ") where\n"
            "\n"
            "import Clash.Prelude (BitVector)\n"
            "\n"
            f"-- | {word_count} 32-bit words ({word_count * 4} bytes).\n"
            f"{sym_name} :: [BitVector 32]\n"
            f"{sym_name} =\n"
        )
        for i, w in enumerate(words):
            sep = "  [ " if i == 0 else "  , "
            f.write(f"{sep}0x{w:08x}\n")
        f.write("  ]\n")

    print(f"gen-bin-hs: wrote {out_path} ({word_count} words = {len(data)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
