# SPDX-FileCopyrightText: 2026 Mika Tammi
# SPDX-License-Identifier: MIT OR BSD-3-Clause
#
# Convert coremark.bin → firmware/phase1/CoreMark.hs with the real
# CoreMark 1.01 bytes baked in as a literal [BitVector 32]. Emitted
# as little-endian 32-bit words (GCC's default for RV32 ILP32),
# padded to exactly 4096 words so the downstream 'listToVecTH'
# call in app/Top.hs gets a full ProgSize-sized vector.
#
# Usage:
#   python3 gen-coremark-hs.py <coremark.bin> <CoreMark.hs>
#
# The output is a complete, standalone replacement for the stub
# 'firmware/phase1/CoreMark.hs' committed in git — same module name,
# same exported symbol, different backing data. Run as part of the
# CoreMark-variant Nix build in 'pkgs/riski5-core/package.nix'.
import struct
import sys

if len(sys.argv) != 3:
    sys.stderr.write("usage: gen-coremark-hs.py <coremark.bin> <CoreMark.hs>\n")
    sys.exit(2)

src_path, dst_path = sys.argv[1], sys.argv[2]

PROG_SIZE_WORDS = 4096
NOP_WORD = 0x0000_0013  # RV32 canonical NOP = addi x0, x0, 0

with open(src_path, "rb") as f:
    data = f.read()

# Pad to multiple of 4 (full word boundary).
pad = (-len(data)) % 4
data += b"\x00" * pad

word_count = len(data) // 4
if word_count > PROG_SIZE_WORDS:
    sys.stderr.write(
        f"error: coremark.bin has {word_count} 32-bit words, "
        f"exceeds ProgSize={PROG_SIZE_WORDS}\n"
    )
    sys.exit(1)

words = list(struct.unpack(f"<{word_count}I", data))

# Pad up to ProgSize with NOPs so the Vec dimension lines up.
words += [NOP_WORD] * (PROG_SIZE_WORDS - word_count)

with open(dst_path, "w") as f:
    f.write(
        "-- SPDX-FileCopyrightText: 2026 Mika Tammi\n"
        "-- SPDX-License-Identifier: MIT OR BSD-3-Clause\n"
        "--\n"
        "-- Auto-generated by pkgs/coremark/gen-coremark-hs.py — DO NOT EDIT.\n"
        "-- Produced from eembc/coremark@v1.01 cross-compiled by\n"
        "-- pkgs/coremark/package.nix against the riski5 platform port\n"
        "-- at firmware/phase2/coremark-port/.\n"
        "{-# LANGUAGE DataKinds #-}\n"
        "{-# LANGUAGE NoStarIsType #-}\n"
        "\n"
        "module CoreMark (\n"
        "  coreMarkFirmwareWords,\n"
        ") where\n"
        "\n"
        "import Clash.Prelude (BitVector)\n"
        "\n"
        f"-- | {word_count} real CoreMark words + "
        f"{PROG_SIZE_WORDS - word_count} NOPs padding = "
        f"{PROG_SIZE_WORDS} total ({PROG_SIZE_WORDS * 4} bytes).\n"
        "coreMarkFirmwareWords :: [BitVector 32]\n"
        "coreMarkFirmwareWords =\n"
    )
    for i, w in enumerate(words):
        sep = "  [ " if i == 0 else "  , "
        f.write(f"{sep}0x{w:08x}\n")
    f.write("  ]\n")
